// Generated by ReScript, PLEASE EDIT WITH CARE


function validStateForMove(board, piece, position) {
  return true;
}

function getPiece(board, position, color) {
  
}

function hasPiece(board, position, color) {
  return false;
}

function checkUnobstructed(board, piece, position, canCapture) {
  return false;
}

export {
  validStateForMove ,
  getPiece ,
  hasPiece ,
  checkUnobstructed ,
  
}
/* No side effect */
