// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Grid from "./Grid.res.js";
import * as Board from "./Board.res.js";
import * as Utils from "./Utils.res.js";
import * as Pieces from "./Pieces.res.js";
import * as Sounds from "./Sounds";
import * as GameUtils from "./GameUtils";
import * as Stdlib_List from "@rescript/runtime/lib/es6/Stdlib_List.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function drawGrid(prim) {
  GameUtils.drawGrid(prim);
}

function endTurn(prim) {
  GameUtils.endTurn();
}

function winSound(prim) {
  Sounds.winSound();
}

function cursorSound(prim) {
  Sounds.cursorSound();
}

function successSound(prim) {
  Sounds.successSound();
}

function failureSound(prim) {
  Sounds.failureSound();
}

function moveSound(prim) {
  Sounds.moveSound();
}

function captureSound(prim) {
  Sounds.captureSound();
}

function turnStartSound(prim) {
  Sounds.turnStartSound(prim);
}

function init() {
  return {
    board: Board.init(),
    turn: "White",
    selectedPiece: undefined,
    legalMoves: undefined,
    cursorPosition: [
      4,
      0
    ],
    promote: false,
    lock: false
  };
}

function draw(state) {
  let grid = Grid.makeGrid(state);
  GameUtils.drawGrid(grid);
  return state;
}

function handleTurnStart(state) {
  let state_board = state.board;
  let state_turn = state.turn;
  let state_cursorPosition = state.cursorPosition;
  let state_promote = state.promote;
  let state_lock = state.lock;
  let state$1 = {
    board: state_board,
    turn: state_turn,
    selectedPiece: undefined,
    legalMoves: undefined,
    cursorPosition: state_cursorPosition,
    promote: state_promote,
    lock: state_lock
  };
  let color = state_turn;
  let otherColor = Utils.oppositeColor(color);
  let ownKing = Stdlib_List.getOrThrow(Stdlib_List.filter(state_board.pieces, p => {
    if (p.TAG === "King") {
      return p._0.color === color;
    } else {
      return false;
    }
  }), 0);
  let otherCoveredPositions = Pieces.getCoveredPositionsForColor(state_board, otherColor);
  let ownKingInCheck = Stdlib_List.has(otherCoveredPositions, ownKing, (param, king) => {
    if (param[0] === Utils.getX(king)) {
      return param[1] === Utils.getY(king);
    } else {
      return false;
    }
  });
  let numLegalMoves = Pieces.getNumLegalMovesForColor(state_board, state_turn);
  if (numLegalMoves === 0) {
    Sounds.winSound();
    if (ownKingInCheck) {
      let winner = Utils.oppositeColor(state_turn);
      alert(winner + ` has won! Refresh the page to play again.`);
    } else {
      alert("Stalemate! Refresh the page to play again.");
    }
    return {
      board: state_board,
      turn: state_turn,
      selectedPiece: undefined,
      legalMoves: undefined,
      cursorPosition: state_cursorPosition,
      promote: state_promote,
      lock: true
    };
  }
  Sounds.turnStartSound(state_turn);
  return draw(state$1);
}

function handleMoveCursor(state) {
  Sounds.cursorSound();
  return draw(state);
}

function handleCancel(state) {
  if (state.lock) {
    return state;
  }
  let match = state.selectedPiece;
  if (match !== undefined) {
    Sounds.successSound();
    return draw({
      board: state.board,
      turn: state.turn,
      selectedPiece: undefined,
      legalMoves: undefined,
      cursorPosition: state.cursorPosition,
      promote: state.promote,
      lock: state.lock
    });
  } else {
    Sounds.failureSound();
    return state;
  }
}

function handleLeft(state) {
  let match = state.cursorPosition;
  if (state.lock) {
    return state;
  }
  let y = match[1];
  let x = match[0];
  let match$1 = state.turn;
  if (match$1 === "White") {
    if (x > 0) {
      return handleMoveCursor({
        board: state.board,
        turn: state.turn,
        selectedPiece: state.selectedPiece,
        legalMoves: state.legalMoves,
        cursorPosition: [
          x - 1 | 0,
          y
        ],
        promote: state.promote,
        lock: state.lock
      });
    } else {
      return state;
    }
  } else if (x < 7) {
    return handleMoveCursor({
      board: state.board,
      turn: state.turn,
      selectedPiece: state.selectedPiece,
      legalMoves: state.legalMoves,
      cursorPosition: [
        x + 1 | 0,
        y
      ],
      promote: state.promote,
      lock: state.lock
    });
  } else {
    return state;
  }
}

function handleRight(state) {
  let match = state.cursorPosition;
  if (state.lock) {
    return state;
  }
  let y = match[1];
  let x = match[0];
  let match$1 = state.turn;
  if (match$1 === "White") {
    if (x < 7) {
      return handleMoveCursor({
        board: state.board,
        turn: state.turn,
        selectedPiece: state.selectedPiece,
        legalMoves: state.legalMoves,
        cursorPosition: [
          x + 1 | 0,
          y
        ],
        promote: state.promote,
        lock: state.lock
      });
    } else {
      return state;
    }
  } else if (x > 0) {
    return handleMoveCursor({
      board: state.board,
      turn: state.turn,
      selectedPiece: state.selectedPiece,
      legalMoves: state.legalMoves,
      cursorPosition: [
        x - 1 | 0,
        y
      ],
      promote: state.promote,
      lock: state.lock
    });
  } else {
    return state;
  }
}

function handleDown(state) {
  let match = state.cursorPosition;
  if (state.lock) {
    return state;
  }
  let y = match[1];
  let x = match[0];
  let match$1 = state.turn;
  if (match$1 === "White") {
    if (y > 0) {
      return handleMoveCursor({
        board: state.board,
        turn: state.turn,
        selectedPiece: state.selectedPiece,
        legalMoves: state.legalMoves,
        cursorPosition: [
          x,
          y - 1 | 0
        ],
        promote: state.promote,
        lock: state.lock
      });
    } else {
      return state;
    }
  } else if (y < 7) {
    return handleMoveCursor({
      board: state.board,
      turn: state.turn,
      selectedPiece: state.selectedPiece,
      legalMoves: state.legalMoves,
      cursorPosition: [
        x,
        y + 1 | 0
      ],
      promote: state.promote,
      lock: state.lock
    });
  } else {
    return state;
  }
}

function handleUp(state) {
  let match = state.cursorPosition;
  if (state.lock) {
    return state;
  }
  let y = match[1];
  let x = match[0];
  let match$1 = state.turn;
  if (match$1 === "White") {
    if (y < 7) {
      return handleMoveCursor({
        board: state.board,
        turn: state.turn,
        selectedPiece: state.selectedPiece,
        legalMoves: state.legalMoves,
        cursorPosition: [
          x,
          y + 1 | 0
        ],
        promote: state.promote,
        lock: state.lock
      });
    } else {
      return state;
    }
  } else if (y > 0) {
    return handleMoveCursor({
      board: state.board,
      turn: state.turn,
      selectedPiece: state.selectedPiece,
      legalMoves: state.legalMoves,
      cursorPosition: [
        x,
        y - 1 | 0
      ],
      promote: state.promote,
      lock: state.lock
    });
  } else {
    return state;
  }
}

function handlePromote(state, key) {
  if (state.promote) {
    let match = state.selectedPiece;
    let maybePiece;
    if (match !== undefined) {
      switch (key) {
        case "b" :
          maybePiece = Utils.bishop(Utils.getColor(match), Utils.getX(match), Utils.getY(match));
          break;
        case "n" :
          maybePiece = Utils.knight(Utils.getColor(match), Utils.getX(match), Utils.getY(match));
          break;
        case "q" :
          maybePiece = Utils.queen(Utils.getColor(match), Utils.getX(match), Utils.getY(match));
          break;
        case "r" :
          maybePiece = Utils.rook(Utils.getColor(match), Utils.getX(match), Utils.getY(match));
          break;
        default:
          maybePiece = undefined;
      }
    } else {
      maybePiece = undefined;
    }
    if (maybePiece !== undefined) {
      let pieces = Stdlib_List.filter(state.board.pieces, p => {
        if (Utils.getX(p) !== Utils.getX(maybePiece)) {
          return true;
        } else {
          return Utils.getY(p) !== Utils.getY(maybePiece);
        }
      });
      let board = {
        pieces: {
          hd: maybePiece,
          tl: pieces
        }
      };
      let state$p_turn = state.turn;
      let state$p_selectedPiece = state.selectedPiece;
      let state$p_legalMoves = state.legalMoves;
      let state$p_cursorPosition = state.cursorPosition;
      let state$p_lock = state.lock;
      let state$p = {
        board: board,
        turn: state$p_turn,
        selectedPiece: state$p_selectedPiece,
        legalMoves: state$p_legalMoves,
        cursorPosition: state$p_cursorPosition,
        promote: false,
        lock: state$p_lock
      };
      Sounds.winSound();
      GameUtils.endTurn();
      return draw(state$p);
    }
    Sounds.failureSound();
    return state;
  }
  Sounds.failureSound();
  return state;
}

function handleSelect(state) {
  if (state.lock) {
    return state;
  }
  let piece = Board.getPiece(state.board, state.cursorPosition, undefined);
  let match = state.cursorPosition;
  let y = match[1];
  let x = match[0];
  let moveHelper = state => {
    let selectedPiece = Stdlib_Option.getOrThrow(state.selectedPiece, undefined);
    let promote = param => {
      if (selectedPiece.TAG === "Pawn") {
        return Utils.promotionRank(selectedPiece._0) === param[1];
      } else {
        return false;
      }
    };
    let legalMove = Stdlib_Option.flatMap(state.legalMoves, moves => Stdlib_List.get(Stdlib_List.filter(moves, param => {
      if (param[0] === x) {
        return param[1] === y;
      } else {
        return false;
      }
    }), 0));
    if (legalMove !== undefined) {
      let state$p_board = Board.confirmMove(state.board, selectedPiece, legalMove, true);
      let state$p_turn = state.turn;
      let state$p_selectedPiece = Utils.withPosition(selectedPiece, legalMove);
      let state$p_legalMoves = state.legalMoves;
      let state$p_cursorPosition = state.cursorPosition;
      let state$p_promote = promote(legalMove);
      let state$p = {
        board: state$p_board,
        turn: state$p_turn,
        selectedPiece: state$p_selectedPiece,
        legalMoves: state$p_legalMoves,
        cursorPosition: state$p_cursorPosition,
        promote: state$p_promote,
        lock: true
      };
      if (Stdlib_List.size(state$p_board.pieces) < Stdlib_List.size(state.board.pieces)) {
        Sounds.captureSound();
      } else {
        Sounds.moveSound();
      }
      if (state$p_promote) {
        return draw(state$p);
      } else {
        GameUtils.endTurn();
        return draw(state$p);
      }
    }
    Sounds.failureSound();
    return state;
  };
  let selectedPiece = state.selectedPiece;
  if (selectedPiece !== undefined) {
    if (piece === undefined) {
      return moveHelper(state);
    }
    if (Utils.getColor(piece) !== state.turn) {
      return moveHelper(state);
    }
    if (x === Utils.getX(selectedPiece) && y === Utils.getY(selectedPiece)) {
      return state;
    }
    let state$p_board = state.board;
    let state$p_turn = state.turn;
    let state$p_legalMoves = Pieces.getLegalMoves(piece, state.board);
    let state$p_cursorPosition = state.cursorPosition;
    let state$p_promote = state.promote;
    let state$p_lock = state.lock;
    let state$p = {
      board: state$p_board,
      turn: state$p_turn,
      selectedPiece: piece,
      legalMoves: state$p_legalMoves,
      cursorPosition: state$p_cursorPosition,
      promote: state$p_promote,
      lock: state$p_lock
    };
    Sounds.successSound();
    return draw(state$p);
  }
  if (piece !== undefined) {
    if (Utils.getColor(piece) === state.turn) {
      let state$p_board$1 = state.board;
      let state$p_turn$1 = state.turn;
      let state$p_selectedPiece = piece;
      let state$p_legalMoves$1 = Pieces.getLegalMoves(piece, state.board);
      let state$p_cursorPosition$1 = state.cursorPosition;
      let state$p_promote$1 = state.promote;
      let state$p_lock$1 = state.lock;
      let state$p$1 = {
        board: state$p_board$1,
        turn: state$p_turn$1,
        selectedPiece: state$p_selectedPiece,
        legalMoves: state$p_legalMoves$1,
        cursorPosition: state$p_cursorPosition$1,
        promote: state$p_promote$1,
        lock: state$p_lock$1
      };
      Sounds.successSound();
      return draw(state$p$1);
    }
    Utils.toggleEmphasis(piece);
    Sounds.successSound();
    return draw(state);
  }
  Sounds.failureSound();
  return state;
}

export {
  drawGrid,
  endTurn,
  winSound,
  cursorSound,
  successSound,
  failureSound,
  moveSound,
  captureSound,
  turnStartSound,
  init,
  draw,
  handleTurnStart,
  handleMoveCursor,
  handleCancel,
  handleLeft,
  handleRight,
  handleDown,
  handleUp,
  handlePromote,
  handleSelect,
}
/* ./Sounds Not a pure module */
