// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Utils from "./Utils.res.mjs";
import * as Pieces from "./Pieces.res.mjs";
import * as Stdlib_List from "@rescript/runtime/lib/es6/Stdlib_List.js";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";

let stroke = 12;

let size = 92;

function positionToId(x, y) {
  return String.fromCharCode(x + 65 | 0) + (y + 1 | 0).toString();
}

function makeSquare(x, y, color) {
  return {
    piece: undefined,
    selection: false,
    movement: false,
    covered: false,
    coveredAndSelected: false,
    x: x,
    y: y,
    color: color,
    id: positionToId(x, y)
  };
}

function makeGrid(state) {
  let match = state.cursorPosition;
  let otherColor = Utils.oppositeColor(state.turn);
  let coveredPositions = Pieces.getCoveredPositionsForColor(state.board, otherColor);
  let emphasizedCoveredPositions = Pieces.getEmphasizedCoveredPositionsForColor(state.board, otherColor);
  let grid = Stdlib_Array.fromInitializer(8, x => Stdlib_Array.fromInitializer(8, y => makeSquare(x, y, state.turn)));
  Stdlib_List.forEach(state.board.pieces, p => {
    grid[Utils.getX(p)][Utils.getY(p)].piece = p;
  });
  Stdlib_List.forEach(coveredPositions, param => {
    grid[param[0]][param[1]].covered = true;
  });
  Stdlib_List.forEach(emphasizedCoveredPositions, param => {
    grid[param[0]][param[1]].coveredAndSelected = true;
  });
  grid[match[0]][match[1]].selection = true;
  let p = state.selectedPiece;
  if (p !== undefined) {
    grid[Utils.getX(p)][Utils.getY(p)].selection = true;
    let l = state.legalMoves;
    if (l !== undefined) {
      Stdlib_List.forEach(l, param => {
        grid[param[0]][param[1]].movement = true;
      });
    }
  }
  return [].concat(...grid);
}

function getInCheck(square) {
  let match = square.piece;
  if (match !== undefined && match.TAG === "King" && match._0.color === square.color) {
    return square.covered;
  } else {
    return false;
  }
}

function getColor(square) {
  if (square.x % 2 === square.y % 2) {
    return "maroon";
  } else {
    return "antiquewhite";
  }
}

function getOverlayColor(square) {
  let inCheck = getInCheck(square);
  let blueOrPurple = square.movement ? (
      square.covered ? "purple" : "blue"
    ) : "none";
  if (square.coveredAndSelected && !square.movement && !inCheck) {
    return "red";
  }
  let match = square.piece;
  if (match !== undefined && !inCheck && !square.movement && square.covered) {
    return "lightcoral";
  } else {
    return blueOrPurple;
  }
}

function getX(square) {
  let match = square.color;
  if (match === "White") {
    return square.x * size | 0;
  } else {
    return (7 - square.x | 0) * size | 0;
  }
}

function getY(square) {
  let match = square.color;
  if (match === "White") {
    return (7 - square.y | 0) * size | 0;
  } else {
    return square.y * size | 0;
  }
}

let scalingFactor = 4;

let assetSize = 23;

export {
  scalingFactor,
  assetSize,
  stroke,
  size,
  positionToId,
  makeSquare,
  makeGrid,
  getInCheck,
  getColor,
  getOverlayColor,
  getX,
  getY,
}
/* No side effect */
