// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Board from "./Board.res.js";
import * as Utils from "./Utils.res.js";
import * as Stdlib_List from "@rescript/runtime/lib/es6/Stdlib_List.js";

function canCover(piece, board, position) {
  let p = Board.getPiece(board, position, undefined);
  if (p !== undefined && (p.TAG === "King" || Utils.getColor(p) === Utils.getColor(piece))) {
    return true;
  } else {
    return Board.checkUnobstructed(board, piece, position, true);
  }
}

function unobstructedPositionsHelper(piece, board, a, b, c, d) {
  let positionHelper = (acc, position) => {
    if (!acc[0]) {
      return [
        false,
        acc[1]
      ];
    }
    let lst = acc[1];
    if (canCover(piece, board, position)) {
      if (Board.hasPiece(board, position, undefined)) {
        return [
          false,
          {
            hd: position,
            tl: lst
          }
        ];
      } else {
        return [
          true,
          {
            hd: position,
            tl: lst
          }
        ];
      }
    } else {
      return [
        false,
        lst
      ];
    }
  };
  return Stdlib_List.flat(Stdlib_List.map({
    hd: a,
    tl: {
      hd: b,
      tl: {
        hd: c,
        tl: {
          hd: d,
          tl: /* [] */0
        }
      }
    }
  }, l => Stdlib_List.reduce(l, [
      true,
      /* [] */0
    ], positionHelper)[1]));
}

function getUnobstructedCardinalPositions(piece, board) {
  let up = Stdlib_List.fromInitializer(7 - Utils.getY(piece) | 0, i => [
    Utils.getX(piece),
    (Utils.getY(piece) + i | 0) + 1 | 0
  ]);
  let down = Stdlib_List.fromInitializer(Utils.getY(piece), i => [
    Utils.getX(piece),
    (Utils.getY(piece) - i | 0) - 1 | 0
  ]);
  let left = Stdlib_List.fromInitializer(Utils.getX(piece), i => [
    (Utils.getX(piece) - i | 0) - 1 | 0,
    Utils.getY(piece)
  ]);
  let right = Stdlib_List.fromInitializer(7 - Utils.getX(piece) | 0, i => [
    (Utils.getX(piece) + i | 0) + 1 | 0,
    Utils.getY(piece)
  ]);
  return unobstructedPositionsHelper(piece, board, up, down, left, right);
}

function getUnobstructedDiagonalPositions(piece, board) {
  let ul = Stdlib_List.fromInitializer(Math.min(Utils.getX(piece), 7 - Utils.getY(piece) | 0), i => [
    (Utils.getX(piece) - i | 0) - 1 | 0,
    (Utils.getY(piece) + i | 0) + 1 | 0
  ]);
  let ur = Stdlib_List.fromInitializer(7 - Math.max(Utils.getX(piece), Utils.getY(piece)) | 0, i => [
    (Utils.getX(piece) + i | 0) + 1 | 0,
    (Utils.getY(piece) + i | 0) + 1 | 0
  ]);
  let dl = Stdlib_List.fromInitializer(Math.min(Utils.getX(piece), Utils.getY(piece)), i => [
    (Utils.getX(piece) - i | 0) - 1 | 0,
    (Utils.getY(piece) - i | 0) - 1 | 0
  ]);
  let dr = Stdlib_List.fromInitializer(Math.min(7 - Utils.getX(piece) | 0, Utils.getY(piece)), i => [
    (Utils.getX(piece) + i | 0) + 1 | 0,
    (Utils.getY(piece) - i | 0) - 1 | 0
  ]);
  return unobstructedPositionsHelper(piece, board, ul, ur, dl, dr);
}

function getCoveredPositions(piece, board) {
  switch (piece.TAG) {
    case "Pawn" :
      let p = piece._0;
      let positions_0 = [
        p.x - 1 | 0,
        p.y + Utils.pawnOffsetHelper(p, 1) | 0
      ];
      let positions_1 = {
        hd: [
          p.x + 1 | 0,
          p.y + Utils.pawnOffsetHelper(p, 1) | 0
        ],
        tl: /* [] */0
      };
      let positions = {
        hd: positions_0,
        tl: positions_1
      };
      return Stdlib_List.filter(positions, param => {
        let y = param[1];
        if (y >= 0 && y <= 7) {
          return canCover(piece, board, [
            param[0],
            y
          ]);
        } else {
          return false;
        }
      });
    case "King" :
      let k = piece._0;
      let positions_0$1 = [
        k.x - 1 | 0,
        k.y
      ];
      let positions_1$1 = {
        hd: [
          k.x - 1 | 0,
          k.y - 1 | 0
        ],
        tl: {
          hd: [
            k.x - 1 | 0,
            k.y + 1 | 0
          ],
          tl: {
            hd: [
              k.x,
              k.y - 1 | 0
            ],
            tl: {
              hd: [
                k.x,
                k.y + 1 | 0
              ],
              tl: {
                hd: [
                  k.x + 1 | 0,
                  k.y
                ],
                tl: {
                  hd: [
                    k.x + 1 | 0,
                    k.y - 1 | 0
                  ],
                  tl: {
                    hd: [
                      k.x + 1 | 0,
                      k.y + 1 | 0
                    ],
                    tl: /* [] */0
                  }
                }
              }
            }
          }
        }
      };
      let positions$1 = {
        hd: positions_0$1,
        tl: positions_1$1
      };
      return Stdlib_List.filter(positions$1, p => canCover(piece, board, p));
    case "Queen" :
      return Stdlib_List.concat(getUnobstructedDiagonalPositions(piece, board), getUnobstructedCardinalPositions(piece, board));
    case "Bishop" :
      return getUnobstructedDiagonalPositions(piece, board);
    case "Knight" :
      let n = piece._0;
      let positions_0$2 = [
        n.x - 2 | 0,
        n.y - 1 | 0
      ];
      let positions_1$2 = {
        hd: [
          n.x - 2 | 0,
          n.y + 1 | 0
        ],
        tl: {
          hd: [
            n.x - 1 | 0,
            n.y + 2 | 0
          ],
          tl: {
            hd: [
              n.x - 1 | 0,
              n.y - 2 | 0
            ],
            tl: {
              hd: [
                n.x + 1 | 0,
                n.y + 2 | 0
              ],
              tl: {
                hd: [
                  n.x + 1 | 0,
                  n.y - 2 | 0
                ],
                tl: {
                  hd: [
                    n.x + 2 | 0,
                    n.y - 1 | 0
                  ],
                  tl: {
                    hd: [
                      n.x + 2 | 0,
                      n.y + 1 | 0
                    ],
                    tl: /* [] */0
                  }
                }
              }
            }
          }
        }
      };
      let positions$2 = {
        hd: positions_0$2,
        tl: positions_1$2
      };
      return Stdlib_List.filter(positions$2, p => canCover(piece, board, p));
    case "Rook" :
      return getUnobstructedCardinalPositions(piece, board);
  }
}

function validBoard(board, movedColor) {
  let ownKing = Stdlib_List.getOrThrow(Stdlib_List.filter(board.pieces, p => {
    if (p.TAG === "King") {
      return p._0.color === movedColor;
    } else {
      return false;
    }
  }), 0);
  let otherCoveredPositions = getCoveredPositionsForColor(board, Utils.oppositeColor(movedColor));
  return !Stdlib_List.has(otherCoveredPositions, [
    Utils.getX(ownKing),
    Utils.getY(ownKing)
  ], (param, param$1) => {
    if (param[0] === param$1[0]) {
      return param[1] === param$1[1];
    } else {
      return false;
    }
  });
}

function coveredPositionsHelper(pieces, board) {
  return Stdlib_List.reduce(Stdlib_List.sort(Stdlib_List.flat(Stdlib_List.reduce(pieces, /* [] */0, (acc, p) => ({
    hd: getCoveredPositions(p, board),
    tl: acc
  }))), (param, param$1) => {
    let x2 = param$1[0];
    let x1 = param[0];
    if (x1 === x2) {
      return param[1] - param$1[1] | 0;
    } else {
      return x1 - x2 | 0;
    }
  }), /* [] */0, (acc, param) => {
    let y1 = param[1];
    let x1 = param[0];
    if (acc === 0) {
      return {
        hd: [
          x1,
          y1
        ],
        tl: /* [] */0
      };
    }
    let match = acc.hd;
    if (x1 === match[0] && y1 === match[1]) {
      return acc;
    } else {
      return {
        hd: [
          x1,
          y1
        ],
        tl: acc
      };
    }
  });
}

function getCoveredPositionsForColor(board, color) {
  return coveredPositionsHelper(Stdlib_List.filter(board.pieces, p => Utils.getColor(p) === color), board);
}

function validStateForMove(board, piece, position) {
  let newBoard = Board.confirmMove(board, piece, position, false);
  return validBoard(newBoard, Utils.getColor(piece));
}

function getLegalMoves(piece, board) {
  switch (piece.TAG) {
    case "Pawn" :
      let p = piece._0;
      let oneSpace_0 = p.x;
      let oneSpace_1 = p.y + Utils.pawnOffsetHelper(p, 1) | 0;
      let oneSpace = [
        oneSpace_0,
        oneSpace_1
      ];
      let twoSpace_0 = p.x;
      let twoSpace_1 = p.y + Utils.pawnOffsetHelper(p, 2) | 0;
      let twoSpace = [
        twoSpace_0,
        twoSpace_1
      ];
      let movement = Board.checkUnobstructed(board, piece, oneSpace, false) ? (
          !p.hasMoved && Board.checkUnobstructed(board, piece, twoSpace, false) ? ({
              hd: oneSpace,
              tl: {
                hd: twoSpace,
                tl: /* [] */0
              }
            }) : ({
              hd: oneSpace,
              tl: /* [] */0
            })
        ) : /* [] */0;
      let capture = Stdlib_List.filter(getCoveredPositions(piece, board), pos => {
        if (Board.hasOppositeColoredPiece(board, pos, p.color)) {
          return true;
        }
        let otherPiece = Board.getPiece(board, [
          pos[0],
          p.y
        ], Utils.oppositeColor(p.color));
        if (otherPiece !== undefined && otherPiece.TAG === "Pawn") {
          return otherPiece._0.hasJustMoved2Spaces;
        } else {
          return false;
        }
      });
      return Stdlib_List.filter(Stdlib_List.concat(movement, capture), pos => validStateForMove(board, {
        TAG: "Pawn",
        _0: p
      }, pos));
    case "King" :
      let k = piece._0;
      let regularMoves = Stdlib_List.filter(getCoveredPositions(piece, board), p => {
        if (Board.checkUnobstructed(board, {
            TAG: "King",
            _0: k
          }, p, true)) {
          return validStateForMove(board, piece, p);
        } else {
          return false;
        }
      });
      if (k.hasMoved || k.inCheck) {
        return regularMoves;
      }
      let y = Utils.backRank(k);
      let leftRook = Board.getPiece(board, [
        0,
        y
      ], k.color);
      let rightRook = Board.getPiece(board, [
        7,
        y
      ], k.color);
      let leftCastle = leftRook !== undefined && leftRook.TAG === "Rook" && !(leftRook._0.hasMoved || Board.hasPiece(board, [
        1,
        y
      ], undefined) || Board.hasPiece(board, [
        2,
        y
      ], undefined) || Board.hasPiece(board, [
        3,
        y
      ], undefined) || !validStateForMove(board, piece, [
        3,
        y
      ]) || !validStateForMove(board, piece, [
        2,
        y
      ]) || !validStateForMove(board, piece, [
        2,
        y
      ])) ? [
          2,
          y
        ] : undefined;
      let rightCastle = rightRook !== undefined && rightRook.TAG === "Rook" && !(rightRook._0.hasMoved || Board.hasPiece(board, [
        5,
        y
      ], undefined) || Board.hasPiece(board, [
        6,
        y
      ], undefined) || !validStateForMove(board, piece, [
        5,
        y
      ]) || !validStateForMove(board, piece, [
        6,
        y
      ]) || !validStateForMove(board, piece, [
        6,
        y
      ])) ? [
          6,
          y
        ] : undefined;
      if (leftCastle !== undefined) {
        if (rightCastle !== undefined) {
          return {
            hd: leftCastle,
            tl: {
              hd: rightCastle,
              tl: regularMoves
            }
          };
        } else {
          return {
            hd: leftCastle,
            tl: regularMoves
          };
        }
      } else if (rightCastle !== undefined) {
        return {
          hd: rightCastle,
          tl: regularMoves
        };
      } else {
        return regularMoves;
      }
    default:
      return Stdlib_List.filter(getCoveredPositions(piece, board), pos => {
        if (Board.checkUnobstructed(board, piece, pos, true)) {
          return validStateForMove(board, piece, pos);
        } else {
          return false;
        }
      });
  }
}

function getEmphasizedCoveredPositionsForColor(board, color) {
  return coveredPositionsHelper(Stdlib_List.filter(board.pieces, p => {
    if (Utils.getColor(p) === color) {
      return Utils.getEmphasis(p);
    } else {
      return false;
    }
  }), board);
}

function getNumLegalMovesForColor(board, color) {
  return Stdlib_List.reduce(Stdlib_List.filter(board.pieces, p => Utils.getColor(p) === color), 0, (acc, x) => acc + Stdlib_List.size(getLegalMoves(x, board)) | 0);
}

export {
  canCover,
  unobstructedPositionsHelper,
  getUnobstructedCardinalPositions,
  getUnobstructedDiagonalPositions,
  getCoveredPositions,
  validStateForMove,
  getLegalMoves,
  coveredPositionsHelper,
  getCoveredPositionsForColor,
  validBoard,
  getEmphasizedCoveredPositionsForColor,
  getNumLegalMovesForColor,
}
/* No side effect */
