// Generated by ReScript, PLEASE EDIT WITH CARE


function oppositeColor(color) {
  if (color === "White") {
    return "Black";
  } else {
    return "White";
  }
}

function getAsset(piece) {
  switch (piece.TAG) {
    case "Pawn" :
      return `assets/` + piece._0.color + `/pawn`;
    case "King" :
      return `assets/` + piece._0.color + `/king`;
    case "Queen" :
      return `assets/` + piece._0.color + `/queen`;
    case "Bishop" :
      return `assets/` + piece._0.color + `/bishop`;
    case "Knight" :
      return `assets/` + piece._0.color + `/knight`;
    case "Rook" :
      return `assets/` + piece._0.color + `/rook`;
  }
}

function getColor(piece) {
  switch (piece.TAG) {
    default:
      return piece._0.color;
  }
}

function getEmphasis(piece) {
  switch (piece.TAG) {
    default:
      return piece._0.emphasizeCoverRange;
  }
}

function toggleEmphasis(piece) {
  switch (piece.TAG) {
    case "Pawn" :
    case "King" :
      break;
    default:
      let x = piece._0;
      x.emphasizeCoverRange = !x.emphasizeCoverRange;
      return;
  }
  let p = piece._0;
  p.emphasizeCoverRange = !p.emphasizeCoverRange;
}

function getX(piece) {
  switch (piece.TAG) {
    default:
      return piece._0.x;
  }
}

function getY(piece) {
  switch (piece.TAG) {
    default:
      return piece._0.y;
  }
}

function withMoved(piece) {
  switch (piece.TAG) {
    case "Pawn" :
      let p = piece._0;
      return {
        TAG: "Pawn",
        _0: {
          x: p.x,
          y: p.y,
          color: p.color,
          hasMoved: true,
          emphasizeCoverRange: p.emphasizeCoverRange,
          hasJustMoved2Spaces: false
        }
      };
    case "King" :
      let k = piece._0;
      return {
        TAG: "King",
        _0: {
          x: k.x,
          y: k.y,
          color: k.color,
          hasMoved: true,
          emphasizeCoverRange: k.emphasizeCoverRange,
          inCheck: k.inCheck
        }
      };
    case "Queen" :
      let p$1 = piece._0;
      return {
        TAG: "Queen",
        _0: {
          x: p$1.x,
          y: p$1.y,
          color: p$1.color,
          hasMoved: true,
          emphasizeCoverRange: p$1.emphasizeCoverRange
        }
      };
    case "Bishop" :
      let p$2 = piece._0;
      return {
        TAG: "Bishop",
        _0: {
          x: p$2.x,
          y: p$2.y,
          color: p$2.color,
          hasMoved: true,
          emphasizeCoverRange: p$2.emphasizeCoverRange
        }
      };
    case "Knight" :
      let p$3 = piece._0;
      return {
        TAG: "Knight",
        _0: {
          x: p$3.x,
          y: p$3.y,
          color: p$3.color,
          hasMoved: true,
          emphasizeCoverRange: p$3.emphasizeCoverRange
        }
      };
    case "Rook" :
      let p$4 = piece._0;
      return {
        TAG: "Rook",
        _0: {
          x: p$4.x,
          y: p$4.y,
          color: p$4.color,
          hasMoved: true,
          emphasizeCoverRange: p$4.emphasizeCoverRange
        }
      };
  }
}

function with2Spaces(p) {
  return {
    TAG: "Pawn",
    _0: {
      x: p.x,
      y: p.y,
      color: p.color,
      hasMoved: true,
      emphasizeCoverRange: p.emphasizeCoverRange,
      hasJustMoved2Spaces: true
    }
  };
}

function disable2Spaces(p) {
  return {
    TAG: "Pawn",
    _0: {
      x: p.x,
      y: p.y,
      color: p.color,
      hasMoved: p.hasMoved,
      emphasizeCoverRange: p.emphasizeCoverRange,
      hasJustMoved2Spaces: false
    }
  };
}

function withPosition(piece, param) {
  let y = param[1];
  let x = param[0];
  switch (piece.TAG) {
    case "Pawn" :
      let p = piece._0;
      return {
        TAG: "Pawn",
        _0: {
          x: x,
          y: y,
          color: p.color,
          hasMoved: p.hasMoved,
          emphasizeCoverRange: p.emphasizeCoverRange,
          hasJustMoved2Spaces: p.hasJustMoved2Spaces
        }
      };
    case "King" :
      let k = piece._0;
      return {
        TAG: "King",
        _0: {
          x: x,
          y: y,
          color: k.color,
          hasMoved: k.hasMoved,
          emphasizeCoverRange: k.emphasizeCoverRange,
          inCheck: k.inCheck
        }
      };
    case "Queen" :
      let p$1 = piece._0;
      return {
        TAG: "Queen",
        _0: {
          x: x,
          y: y,
          color: p$1.color,
          hasMoved: p$1.hasMoved,
          emphasizeCoverRange: p$1.emphasizeCoverRange
        }
      };
    case "Bishop" :
      let p$2 = piece._0;
      return {
        TAG: "Bishop",
        _0: {
          x: x,
          y: y,
          color: p$2.color,
          hasMoved: p$2.hasMoved,
          emphasizeCoverRange: p$2.emphasizeCoverRange
        }
      };
    case "Knight" :
      let p$3 = piece._0;
      return {
        TAG: "Knight",
        _0: {
          x: x,
          y: y,
          color: p$3.color,
          hasMoved: p$3.hasMoved,
          emphasizeCoverRange: p$3.emphasizeCoverRange
        }
      };
    case "Rook" :
      let p$4 = piece._0;
      return {
        TAG: "Rook",
        _0: {
          x: x,
          y: y,
          color: p$4.color,
          hasMoved: p$4.hasMoved,
          emphasizeCoverRange: p$4.emphasizeCoverRange
        }
      };
  }
}

function promotionRank(p) {
  let match = p.color;
  if (match === "White") {
    return 7;
  } else {
    return 0;
  }
}

function backRank(p) {
  let match = p.color;
  if (match === "White") {
    return 0;
  } else {
    return 7;
  }
}

function pawnOffsetHelper(p, n) {
  let match = p.color;
  if (match === "White") {
    return n;
  } else {
    return -n | 0;
  }
}

function pawn(color, x, y) {
  return {
    TAG: "Pawn",
    _0: {
      x: x,
      y: y,
      color: color,
      hasMoved: false,
      emphasizeCoverRange: false,
      hasJustMoved2Spaces: false
    }
  };
}

function king(color, x, y) {
  return {
    TAG: "King",
    _0: {
      x: x,
      y: y,
      color: color,
      hasMoved: false,
      emphasizeCoverRange: false,
      inCheck: false
    }
  };
}

function queen(color, x, y) {
  return {
    TAG: "Queen",
    _0: {
      x: x,
      y: y,
      color: color,
      hasMoved: false,
      emphasizeCoverRange: false
    }
  };
}

function rook(color, x, y) {
  return {
    TAG: "Rook",
    _0: {
      x: x,
      y: y,
      color: color,
      hasMoved: false,
      emphasizeCoverRange: false
    }
  };
}

function bishop(color, x, y) {
  return {
    TAG: "Bishop",
    _0: {
      x: x,
      y: y,
      color: color,
      hasMoved: false,
      emphasizeCoverRange: false
    }
  };
}

function knight(color, x, y) {
  return {
    TAG: "Knight",
    _0: {
      x: x,
      y: y,
      color: color,
      hasMoved: false,
      emphasizeCoverRange: false
    }
  };
}

export {
  oppositeColor,
  getAsset,
  getColor,
  getEmphasis,
  toggleEmphasis,
  getX,
  getY,
  withMoved,
  with2Spaces,
  disable2Spaces,
  withPosition,
  promotionRank,
  backRank,
  pawnOffsetHelper,
  pawn,
  king,
  queen,
  rook,
  bishop,
  knight,
}
/* No side effect */
