// Generated by ReScript, PLEASE EDIT WITH CARE


function oppositeColor(color) {
  if (color) {
    return /* White */0;
  } else {
    return /* Black */1;
  }
}

function colorName(color) {
  if (color) {
    return "Black";
  } else {
    return "White";
  }
}

var scalingFactor = 4;

var assetSize = 23;

export {
  scalingFactor ,
  assetSize ,
  oppositeColor ,
  colorName ,
  
}
/* No side effect */
